
print("🐛 BUG FOUND:")
print("Line 198: if df: st.session_state.company_db = CompanyDatabase(df)")
print("\n❌ WRONG: 'if df:' - doesn't work with pandas DataFrames")
print("✅ RIGHT: 'if df is not None:' - proper check for DataFrame")
print("\n" + "="*70)
print("QUICK FIX:")
print("="*70)
print("\nIn your GitHub file, find line 198 and change:")
print("\nFROM:")
print("  if df: st.session_state.company_db = CompanyDatabase(df); st.rerun()")
print("\nTO:")
print("  if df is not None: st.session_state.company_db = CompanyDatabase(df); st.rerun()")
print("\n" + "="*70)
print("ALL LINES TO FIX:")
print("="*70)
print("Line 198: if df: → if df is not None:")
print("Line 201: if up: → if up is not None:")
print("\nThese are the only 2 lines that need fixing!")
